browser=chrome
amazonUrl=https://www.amazon.com.tr
googleUrl=https://www.google.com
aramaKelimesi=Samsung
testUrl=https://the-internet.herokuapp.com/login
registerUrl=https://practice.expandtesting.com/register
expandtestingUrl=https://practice.expandtesting.com/login